Repository kirstybrown/back-budget-calculator, pull requests merged in 2022-01, with the labels that each got.

#4 Issue/begin backend #2
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  .idea/sonarlint/issuestore/index.pb
  .idea/vcs.xml
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.properties
  HELP.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/budgetcalculator/budgetcalculatorapi/BudgetcalculatorApiApplication.java
  src/main/java/com/budgetcalculator/budgetcalculatorapi/controller/HelloWorldController.java
  src/main/resources/application.properties
  src/test/java/com/budgetcalculator/budgetcalculatorapi/BudgetcalculatorApiApplicationTests.java
  target/classes/application.properties
Labels: configuration

#8 Issue/add getbyid #7
  src/main/java/com/budgetcalculator/api/ExpenseController.java
  src/main/java/com/budgetcalculator/application/usecase/ListExpensesUseCaseImpl.java
Labels: feature

#12 Issue/create mysql db#9
  pom.xml
  src/main/java/com/budgetcalculator/api/ExpenseController.java
  src/main/java/com/budgetcalculator/application/query_service/ListExpensesUseCase.java
  src/main/java/com/budgetcalculator/application/repository/ExpenseRepository.java
  src/main/java/com/budgetcalculator/application/usecase/ListExpensesUseCaseImpl.java
  src/main/java/com/budgetcalculator/domain/model/aggregate/Expense.java
  src/main/java/com/budgetcalculator/domain/model/value_object/Category.java
  src/main/resources/application.properties
  src/main/resources/import.sql
Labels: feature, configuration

#18 Issue/exceptions manager #14
  .gitignore
  src/main/java/com/budgetcalculator/api/ExpenseController.java
  src/main/java/com/budgetcalculator/api/exception/ControllerExceptionHandler.java
  src/main/java/com/budgetcalculator/api/exception/ErrorMessage.java
  src/main/java/com/budgetcalculator/api/exception/ResourceNotFoundException.java
  src/main/java/com/budgetcalculator/application/usecase/ListExpensesUseCaseImpl.java
Labels: feature
